// Optional, user-enabled installer for the account-wide usage chip.
//
// IMPORTANT trust boundary: the Aya PROCESS never reads your auth token and
// never calls Anthropic. This installer only writes a shell script + a Claude
// Code "Stop" hook into ~/.claude/settings.json. The token read + the call to
// the (undocumented, unsupported) usage endpoint happen later, in that separate
// shell script, run by Claude Code — not in Aya. Aya only ever reads the plain
// JSON file the script writes (see electron/usage.ts).
//
// Enabling is explicit (a Settings toggle with a full-disclosure dialog) and
// fully reversible — uninstall removes the hook entry and the script.

import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { writeFileAtomic } from "./atomic-write";
import { AYA_HOME, USAGE_FILE } from "./paths";

const CLAUDE_SETTINGS_FILE = path.join(os.homedir(), ".claude", "settings.json");
// The generated fetch script lives in Aya's own dir (always exists), referenced
// by absolute path from the hook entry.
export const HOOK_SCRIPT_FILE = path.join(AYA_HOME, "aya-usage-hook.sh");

export interface UsageHookStatus {
  installed: boolean;
  /** Absolute path to the generated script (whether or not it exists yet). */
  scriptPath: string;
  /** Where the hook is registered. */
  settingsPath: string;
}

// ---- pure settings.json merge/unmerge (the risky part — unit-tested) --------

type StopEntry = { hooks?: Array<{ type?: string; command?: string }> };

/** True if settings already register a Stop hook whose command is `command`. */
export function hasStopHook(settings: unknown, command: string): boolean {
  if (typeof settings !== "object" || settings === null) return false;
  const hooks = (settings as Record<string, unknown>).hooks;
  if (typeof hooks !== "object" || hooks === null) return false;
  const stop = (hooks as Record<string, unknown>).Stop;
  if (!Array.isArray(stop)) return false;
  return stop.some(
    (e: StopEntry) =>
      Array.isArray(e?.hooks) &&
      e.hooks.some((h) => h?.command === command),
  );
}

/** Return a NEW settings object with our Stop hook added (idempotent), leaving
 *  every other key — and any other Stop hooks — untouched. */
export function withStopHook(
  settings: Record<string, unknown>,
  command: string,
): Record<string, unknown> {
  if (hasStopHook(settings, command)) return settings;
  const hooks = { ...((settings.hooks as Record<string, unknown>) ?? {}) };
  const stop = Array.isArray(hooks.Stop) ? [...hooks.Stop] : [];
  stop.push({ hooks: [{ type: "command", command }] });
  return { ...settings, hooks: { ...hooks, Stop: stop } };
}

/** Return a NEW settings object with our Stop hook removed, leaving everything
 *  else intact. Drops now-empty Stop / hooks containers so we don't leave
 *  litter, but never touches other people's hooks. */
export function withoutStopHook(
  settings: Record<string, unknown>,
  command: string,
): Record<string, unknown> {
  const hooks = settings.hooks;
  if (typeof hooks !== "object" || hooks === null) return settings;
  const h = hooks as Record<string, unknown>;
  if (!Array.isArray(h.Stop)) return settings;
  const stop = (h.Stop as StopEntry[]).filter(
    (e) => !(Array.isArray(e?.hooks) && e.hooks.some((x) => x?.command === command)),
  );
  const nextHooks: Record<string, unknown> = { ...h };
  if (stop.length > 0) nextHooks.Stop = stop;
  else delete nextHooks.Stop;
  const next: Record<string, unknown> = { ...settings };
  if (Object.keys(nextHooks).length > 0) next.hooks = nextHooks;
  else delete next.hooks;
  return next;
}

// ---- the generated fetch script ---------------------------------------------

/** The shell script the hook runs. Throttled; reads the token from the OS
 *  credential store; calls the usage endpoint; writes Aya's file shape. Exits
 *  quietly on any missing dependency or failure so it never breaks a session. */
export function hookScriptSource(outFile: string): string {
  return `#!/usr/bin/env bash
# Auto-generated by Aya (Settings -> usage chip). Writes the account-wide usage
# snapshot Aya reads. It calls Anthropic's UNDOCUMENTED usage endpoint with your
# OWN token — unsupported, may change. Remove it from Aya Settings.
set -euo pipefail
OUT=${JSON.stringify(outFile)}
command -v jq >/dev/null 2>&1 || exit 0
command -v curl >/dev/null 2>&1 || exit 0
# Throttle: skip if written in the last 5 minutes.
if [ -f "$OUT" ]; then
  now=$(date +%s)
  mod=$(stat -f %m "$OUT" 2>/dev/null || stat -c %Y "$OUT" 2>/dev/null || echo 0)
  [ $((now - mod)) -lt 300 ] && exit 0
fi
# Claude Code OAuth token: macOS Keychain, else Linux credentials file.
if RAW=$(security find-generic-password -s 'Claude Code-credentials' -w 2>/dev/null); then
  :
elif [ -f "$HOME/.claude/.credentials.json" ]; then
  RAW=$(cat "$HOME/.claude/.credentials.json")
else
  exit 0
fi
TOKEN=$(printf '%s' "$RAW" | jq -r '.claudeAiOauth.accessToken // empty')
[ -n "$TOKEN" ] || exit 0
RESP=$(curl -sS -m 10 -H "Authorization: Bearer $TOKEN" \\
  https://api.anthropic.com/api/oauth/usage) || exit 0
mkdir -p "$(dirname "$OUT")"
printf '%s' "$RESP" | jq \\
  --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \\
  '{fiveHour:{pct:.five_hour.utilization, resetsAt:.five_hour.resets_at},
    sevenDay:{pct:.seven_day.utilization, resetsAt:.seven_day.resets_at},
    updatedAt:$ts}' > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
`;
}

// ---- fs-bound install / uninstall / status ----------------------------------

async function readSettings(): Promise<Record<string, unknown>> {
  try {
    const raw = await fs.readFile(CLAUDE_SETTINGS_FILE, "utf-8");
    const parsed = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      throw new Error("settings.json is not an object");
    }
    return parsed as Record<string, unknown>;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw err; // malformed existing file — refuse to clobber it
  }
}

export async function usageHookStatus(): Promise<UsageHookStatus> {
  let registered = false;
  try {
    registered = hasStopHook(await readSettings(), HOOK_SCRIPT_FILE);
  } catch {
    registered = false;
  }
  let scriptExists = false;
  try {
    await fs.access(HOOK_SCRIPT_FILE);
    scriptExists = true;
  } catch {
    scriptExists = false;
  }
  return {
    installed: registered && scriptExists,
    scriptPath: HOOK_SCRIPT_FILE,
    settingsPath: CLAUDE_SETTINGS_FILE,
  };
}

export async function installUsageHook(): Promise<UsageHookStatus> {
  const settings = await readSettings();
  const next = withStopHook(settings, HOOK_SCRIPT_FILE);
  await writeFileAtomic(CLAUDE_SETTINGS_FILE, JSON.stringify(next, null, 2) + "\n");
  await writeFileAtomic(HOOK_SCRIPT_FILE, hookScriptSource(USAGE_FILE));
  await fs.chmod(HOOK_SCRIPT_FILE, 0o755);
  return usageHookStatus();
}

export async function uninstallUsageHook(): Promise<UsageHookStatus> {
  try {
    const settings = await readSettings();
    const next = withoutStopHook(settings, HOOK_SCRIPT_FILE);
    await writeFileAtomic(
      CLAUDE_SETTINGS_FILE,
      JSON.stringify(next, null, 2) + "\n",
    );
  } catch {
    /* malformed/unreadable settings — leave it alone */
  }
  await fs.rm(HOOK_SCRIPT_FILE, { force: true });
  return usageHookStatus();
}
